In [57]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from scipy import stats
from sklearn.preprocessing import MinMaxScaler

In [59]:
raw_data = pd.read_excel('weather-sa-2017-2019-v4.xlsx')

In [60]:
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain
0,Qassim,2017-01-01,2017,1.0,1.0,24,0,17,11,64.0,1018.0,16,False
1,Qassim,2017-01-01,2017,1.0,1.0,1,0,17,6,64.0,1018.0,16,False
2,Qassim,2017-01-01,2017,1.0,1.0,3,0,15,11,72.0,1019.0,16,False
3,Qassim,2017-01-01,2017,1.0,1.0,4,0,15,11,72.0,1019.0,16,False
4,Qassim,2017-01-01,2017,1.0,1.0,5,0,15,9,72.0,1019.0,16,False

In [61]:

raw_data = raw_data.drop_duplicates()
raw_data = raw_data.replace('ERR', np.nan)
raw_data = raw_data.replace(-1, np.nan)
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249023 entries, 0 to 249024
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        249020 non-null  object
 1   date        249023 non-null  datetime64[ns]
 2   year        249023 non-null  int64
 3   month       249021 non-null  float64
 4   day         249022 non-null  float64
 5   hour        249023 non-null  int64
 6   minute      249023 non-null  int64
 7   temp        248985 non-null  float64
 8   wind        248914 non-null  float64
 9   humidity    249006 non-null  float64
 10  barometer   248951 non-null  float64
 11  visibility  199379 non-null  float64
 12  rain        249023 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(7), int64(3), object(1)
memory usage: 24.9+ MB

In [62]:
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
raw_data[['temp','wind','humidity','barometer','visibility']]=imputer.fit_transform(raw_data[['temp','wind','humidity','barometer','visibility']])
raw_data

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain
0,Qassim,2017-01-01,2017,1.0,1.0,24,0,17.0,11.0,64.0,1018.0,16.00000,False
1,Qassim,2017-01-01,2017,1.0,1.0,1,0,17.0,6.0,64.0,1018.0,16.00000,False
2,Qassim,2017-01-01,2017,1.0,1.0,3,0,15.0,11.0,72.0,1019.0,16.00000,False
3,Qassim,2017-01-01,2017,1.0,1.0,4,0,15.0,11.0,72.0,1019.0,16.00000,False
4,Qassim,2017-01-01,2017,1.0,1.0,5,0,15.0,9.0,72.0,1019.0,16.00000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249020,Jawf,2019-04-30,2019,4.0,30.0,19,0,32.0,19.0,14.0,1014.0,14.05468,False
249021,Jawf,2019-04-30,2019,4.0,30.0,20,0,29.0,9.0,22.0,1015.0,14.05468,False
249022,Jawf,2019-04-30,2019,4.0,30.0,21,0,27.0,7.0,24.0,1016.0,14.05468,False
249023,Jawf,2019-04-30,2019,4.0,30.0,22,0,26.0,0.0,26.0,1017.0,16.00000,False
249024,Jawf,2019-04-30,2019,4.0,30.0,23,0,24.0,7.0,29.0,1017.0,16.00000,False

In [63]:

raw_data.dropna(inplace=True)
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249017 entries, 0 to 249024
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        249017 non-null  object
 1   date        249017 non-null  datetime64[ns]
 2   year        249017 non-null  int64
 3   month       249017 non-null  float64
 4   day         249017 non-null  float64
 5   hour        249017 non-null  int64
 6   minute      249017 non-null  int64
 7   temp        249017 non-null  float64
 8   wind        249017 non-null  float64
 9   humidity    249017 non-null  float64
 10  barometer   249017 non-null  float64
 11  visibility  249017 non-null  float64
 12  rain        249017 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(7), int64(3), object(1)
memory usage: 24.9+ MB

In [64]:
raw_data['city']=raw_data['city'].astype(str)
raw_data['month']=raw_data['month'].astype(int)
raw_data['day']=raw_data['day'].astype(int)
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249017 entries, 0 to 249024
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   city        249017 non-null  object
 1   date        249017 non-null  datetime64[ns]
 2   year        249017 non-null  int64
 3   month       249017 non-null  int32
 4   day         249017 non-null  int32
 5   hour        249017 non-null  int64
 6   minute      249017 non-null  int64
 7   temp        249017 non-null  float64
 8   wind        249017 non-null  float64
 9   humidity    249017 non-null  float64
 10  barometer   249017 non-null  float64
 11  visibility  249017 non-null  float64
 12  rain        249017 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int32(2), int64(3), object(1)
memory usage: 23.0+ MB

In [65]:
print(raw_data['city'].unique())

['Qassim' 'Hail' 'Madina' 'EP' 'Riyadh' 'Mecca' 'Tabuk' 'Assir'
 'Northern boarder' 'Jazan' 'Najran' 'Al-baha' 'Baha' 'Jawf']

In [66]:
raw_data['city']=raw_data['city'].replace('EP','Eastern Province')
raw_data['city']=raw_data['city'].replace('Baha','Al-baha')
print(raw_data['city'].unique())

['Qassim' 'Hail' 'Madina' 'Eastern Province' 'Riyadh' 'Mecca' 'Tabuk'
 'Assir' 'Northern boarder' 'Jazan' 'Najran' 'Al-baha' 'Jawf']

In [67]:
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,False
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,False
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,False
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,False
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,False

In [68]:
raw_data['rain'] = raw_data['rain'].astype(bool).map({False: 0, True: 1})
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,0
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,0
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,0
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,0
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,0

In [69]:

numeric_columns = raw_data.select_dtypes(include=['float64', 'int64']).columns

for column in numeric_columns:
    Q1 = raw_data[column].quantile(0.25)
    Q3 = raw_data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    raw_data = raw_data[(raw_data[column] >= lower_bound) & (raw_data[column] <= upper_bound)]

In [70]:
def time_of_day(time):
    if 5 <= time < 12:
        return 'Morning'
    elif 12 <= time < 18:
        return 'Afternoon'
    elif 18 <= time < 24:
        return 'Evening'
    else:
        return 'Night'

raw_data['time'] = raw_data['hour'].apply(lambda x: time_of_day(x))
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain,time
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,0,Night
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,0,Night
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,0,Night
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,0,Night
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,0,Morning

In [71]:
def wind_category(windSpeed):
    if windSpeed < 10:
        return 'Low'
    elif 10 <= windSpeed < 20:
        return 'Medium'
    else:
        return 'High'

raw_data['windSpeed'] = raw_data['wind'].apply(lambda x: wind_category(x))
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain,time,windSpeed
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,0,Night,Medium
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,0,Night,Low
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,0,Night,Medium
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,0,Night,Medium
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,0,Morning,Low

In [72]:
raw_data['time'] = raw_data['time'].astype(str).map({'Morning': 0, 'Afternoon': 1,'Evening': 2,'Night':3 })

raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain,time,windSpeed
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,0,3,Medium
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,0,3,Low
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,0,3,Medium
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,0,3,Medium
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,0,0,Low

In [73]:
raw_data['windSpeed'] = raw_data['windSpeed'].astype(str).map({'Low': 0, 'Medium': 1,'High': 2 })
raw_data.head()

,city,date,year,month,day,hour,minute,temp,wind,humidity,barometer,visibility,rain,time,windSpeed
0,Qassim,2017-01-01,2017,1,1,24,0,17.0,11.0,64.0,1018.0,16.0,0,3,1
1,Qassim,2017-01-01,2017,1,1,1,0,17.0,6.0,64.0,1018.0,16.0,0,3,0
2,Qassim,2017-01-01,2017,1,1,3,0,15.0,11.0,72.0,1019.0,16.0,0,3,1
3,Qassim,2017-01-01,2017,1,1,4,0,15.0,11.0,72.0,1019.0,16.0,0,3,1
4,Qassim,2017-01-01,2017,1,1,5,0,15.0,9.0,72.0,1019.0,16.0,0,0,0

In [74]:
raw_data = pd.get_dummies(raw_data, columns=['city']).astype('int64')
raw_data.head()

,date,year,month,day,hour,minute,temp,wind,humidity,barometer,...,city_Hail,city_Jawf,city_Jazan,city_Madina,city_Mecca,city_Najran,city_Northern boarder,city_Qassim,city_Riyadh,city_Tabuk
0,1483228800000000000,2017,1,1,24,0,17,11,64,1018,...,0,0,0,0,0,0,0,1,0,0
1,1483228800000000000,2017,1,1,1,0,17,6,64,1018,...,0,0,0,0,0,0,0,1,0,0
2,1483228800000000000,2017,1,1,3,0,15,11,72,1019,...,0,0,0,0,0,0,0,1,0,0
3,1483228800000000000,2017,1,1,4,0,15,11,72,1019,...,0,0,0,0,0,0,0,1,0,0
4,1483228800000000000,2017,1,1,5,0,15,9,72,1019,...,0,0,0,0,0,0,0,1,0,0

In [75]:
raw_data['date']= pd.to_datetime(raw_data['date'], unit='ns')
raw_data

,date,year,month,day,hour,minute,temp,wind,humidity,barometer,...,city_Hail,city_Jawf,city_Jazan,city_Madina,city_Mecca,city_Najran,city_Northern boarder,city_Qassim,city_Riyadh,city_Tabuk
0,2017-01-01,2017,1,1,24,0,17,11,64,1018,...,0,0,0,0,0,0,0,1,0,0
1,2017-01-01,2017,1,1,1,0,17,6,64,1018,...,0,0,0,0,0,0,0,1,0,0
2,2017-01-01,2017,1,1,3,0,15,11,72,1019,...,0,0,0,0,0,0,0,1,0,0
3,2017-01-01,2017,1,1,4,0,15,11,72,1019,...,0,0,0,0,0,0,0,1,0,0
4,2017-01-01,2017,1,1,5,0,15,9,72,1019,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249020,2019-04-30,2019,4,30,19,0,32,19,14,1014,...,0,1,0,0,0,0,0,0,0,0
249021,2019-04-30,2019,4,30,20,0,29,9,22,1015,...,0,1,0,0,0,0,0,0,0,0
249022,2019-04-30,2019,4,30,21,0,27,7,24,1016,...,0,1,0,0,0,0,0,0,0,0
249023,2019-04-30,2019,4,30,22,0,26,0,26,1017,...,0,1,0,0,0,0,0,0,0,0
249024,2019-04-30,2019,4,30,23,0,24,7,29,1017,...,0,1,0,0,0,0,0,0,0,0

In [76]:
raw_data.drop(["date","rain","minute"],inplace=True,axis=1)
raw_data.head()

,year,month,day,hour,temp,wind,humidity,barometer,visibility,time,...,city_Hail,city_Jawf,city_Jazan,city_Madina,city_Mecca,city_Najran,city_Northern boarder,city_Qassim,city_Riyadh,city_Tabuk
0,2017,1,1,24,17,11,64,1018,16,3,...,0,0,0,0,0,0,0,1,0,0
1,2017,1,1,1,17,6,64,1018,16,3,...,0,0,0,0,0,0,0,1,0,0
2,2017,1,1,3,15,11,72,1019,16,3,...,0,0,0,0,0,0,0,1,0,0
3,2017,1,1,4,15,11,72,1019,16,3,...,0,0,0,0,0,0,0,1,0,0
4,2017,1,1,5,15,9,72,1019,16,0,...,0,0,0,0,0,0,0,1,0,0

In [77]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 207112 entries, 0 to 249024
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   year                   207112 non-null  int64
 1   month                  207112 non-null  int64
 2   day                    207112 non-null  int64
 3   hour                   207112 non-null  int64
 4   temp                   207112 non-null  int64
 5   wind                   207112 non-null  int64
 6   humidity               207112 non-null  int64
 7   barometer              207112 non-null  int64
 8   visibility             207112 non-null  int64
 9   time                   207112 non-null  int64
 10  windSpeed              207112 non-null  int64
 11  city_Al-baha           207112 non-null  int64
 12  city_Assir             207112 non-null  int64
 13  city_Eastern Province  207112 non-null  int64
 14  city_Hail              207112 non-null  int64
 15  city_Jawf              207112 non-null  int64
 16  city_Jazan             207112 non-null  int64
 17  city_Madina            207112 non-null  int64
 18  city_Mecca             207112 non-null  int64
 19  city_Najran            207112 non-null  int64
 20  city_Northern boarder  207112 non-null  int64
 21  city_Qassim            207112 non-null  int64
 22  city_Riyadh            207112 non-null  int64
 23  city_Tabuk             207112 non-null  int64
dtypes: int64(24)
memory usage: 39.5 MB

In [78]:
scaler = MinMaxScaler()
ml_data = scaler.fit_transform(raw_data)
ml_data

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.27272727, 0.96666667, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.27272727, 0.96666667, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.27272727, 0.96666667, ..., 0.        , 0.        ,
        0.        ]])

In [79]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 207112 entries, 0 to 249024
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   year                   207112 non-null  int64
 1   month                  207112 non-null  int64
 2   day                    207112 non-null  int64
 3   hour                   207112 non-null  int64
 4   temp                   207112 non-null  int64
 5   wind                   207112 non-null  int64
 6   humidity               207112 non-null  int64
 7   barometer              207112 non-null  int64
 8   visibility             207112 non-null  int64
 9   time                   207112 non-null  int64
 10  windSpeed              207112 non-null  int64
 11  city_Al-baha           207112 non-null  int64
 12  city_Assir             207112 non-null  int64
 13  city_Eastern Province  207112 non-null  int64
 14  city_Hail              207112 non-null  int64
 15  city_Jawf              207112 non-null  int64
 16  city_Jazan             207112 non-null  int64
 17  city_Madina            207112 non-null  int64
 18  city_Mecca             207112 non-null  int64
 19  city_Najran            207112 non-null  int64
 20  city_Northern boarder  207112 non-null  int64
 21  city_Qassim            207112 non-null  int64
 22  city_Riyadh            207112 non-null  int64
 23  city_Tabuk             207112 non-null  int64
dtypes: int64(24)
memory usage: 39.5 MB

In [80]:
#data16=pd.DataFrame(raw_data)
#data16.to_excel('16NewWeather-sa-2017-2019-v4.xlsx', index=False)

In [81]:
#data10=pd.DataFrame(ml_data)
#data10.to_excel('10NewWeather-sa-2017-2019-v4.xlsx', index=False)